openapi: 3.0.0
info:
  title: API de Exemplo
  description: API simples com Node.js e Swagger
  version: 1.0.0
paths:
  /:
    get:
      summary: Retorna uma mensagem de ol치
      responses:
        '200':
          description: Mensagem de ol치
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Ol치, mundo!"
  /hello:
    get:
      summary: Retorna uma mensagem personalizada
      responses:
        '200':
          description: Mensagem personalizada
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Ol치 do servidor Node.js!"
